name: Minion
version: 1.9.1
api: 3.0.0
main: CLADevs\Minion\Main
author: CLADevs

commands:
  minion:
    description: "get the Minion Spawner!"
permissions:
  minion.commands:
    description: "/minion command permission"
    default: op
  minion.open.others:
    description: "Open other people minions"
    default: op
